# Generated by Django 4.2.2 on 2023-06-14 10:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('min_trade_amount', models.FloatField()),
                ('discount', models.FloatField()),
            ],
        ),
    ]
