# Generated by Django 4.2.2 on 2023-06-14 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='discount',
            field=models.FloatField(default=0),
        ),
    ]
