# Generated by Django 4.2.2 on 2023-06-14 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade_hub', '0008_remove_useritem_price'),
        ('market', '0002_marketitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketitem',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to='trade_hub.useritem'),
        ),
    ]
