# Generated by Django 4.2.2 on 2023-06-14 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_discount'),
        ('market', '0003_marketitem_buyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketitem',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seller', to='users.profile'),
        ),
        migrations.AlterField(
            model_name='marketitem',
            name='buyer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to='users.profile'),
        ),
    ]
