# Generated by Django 4.2.2 on 2023-06-09 12:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=500)),
                ('short_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('stattrak', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, default='items/empty_trade_slot.png', upload_to='items/')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(choices=[('N', 'New'), ('RW', 'Reviewing'), ('DC', 'Declined'), ('CD', 'Canceled'), ('SC', 'Success')], default='N', max_length=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator', to='users.profile')),
                ('guarantor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guarantor', to='users.profile')),
                ('second_party', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_party', to='users.profile')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='UserItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('float', models.DecimalField(blank=True, decimal_places=17, max_digits=18, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade_hub.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
        migrations.CreateModel(
            name='TradeItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade_hub.item')),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade_hub.trade')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.profile')),
            ],
        ),
        migrations.CreateModel(
            name='ItemQuality',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=500)),
                ('color_hex', models.CharField(default='#FFFFFF', max_length=9)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade_hub.game')),
            ],
        ),
        migrations.CreateModel(
            name='ItemExterior',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=500)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade_hub.game')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='exterior',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trade_hub.itemexterior'),
        ),
        migrations.AddField(
            model_name='item',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade_hub.game'),
        ),
        migrations.AddField(
            model_name='item',
            name='quality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trade_hub.itemquality'),
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('name', 'stattrak', 'quality', 'exterior')},
        ),
    ]
