# Generated by Django 4.2.2 on 2023-06-12 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_hub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useritem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
