# Generated by Django 4.2.2 on 2023-06-12 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade_hub', '0002_alter_useritem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradeitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade_hub.useritem'),
        ),
    ]
