# Generated by Django 4.2.2 on 2023-06-12 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade_hub', '0003_alter_tradeitem_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tradeitem',
            old_name='item',
            new_name='user_item',
        ),
    ]
