# Generated by Django 4.2.2 on 2023-06-12 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_discount'),
        ('trade_hub', '0004_rename_item_tradeitem_user_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='guarantor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guarantor', to='users.profile'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='second_party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_party', to='users.profile'),
        ),
    ]
