# Generated by Django 4.2.2 on 2023-06-12 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_discount'),
        ('trade_hub', '0005_alter_trade_guarantor_alter_trade_second_party'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradeitem',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trade_hub.item'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='users.profile'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='guarantor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guarantor', to='users.profile'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='second_party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_party', to='users.profile'),
        ),
        migrations.AlterField(
            model_name='tradeitem',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
        migrations.AlterField(
            model_name='tradeitem',
            name='user_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trade_hub.useritem'),
        ),
    ]
