# Generated by Django 4.2.2 on 2023-06-13 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_discount'),
        ('trade_hub', '0006_tradeitem_item_alter_trade_creator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useritem',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
    ]
