# Generated by Django 4.2.2 on 2023-06-14 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade_hub', '0007_alter_useritem_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useritem',
            name='price',
        ),
    ]
